# Generated by Django 2.1.1 on 2018-09-14 06:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter title for this schedule', max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Enter a subject', max_length=200)),
                ('total_time_req', models.IntegerField(help_text='Enter total time required')),
                ('satisfied', models.BooleanField(help_text='Check if this service has been satisfied')),
                ('service_type', models.CharField(blank=True, choices=[('PI', 'Push-In'), ('PO', 'Pull-Out')], default=None, help_text='Service type', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(help_text='Enter duration of this service')),
                ('day', models.CharField(choices=[('M', 'Monday'), ('Tu', 'Tuesday'), ('W', 'Wednesday'), ('Th', 'Thursday'), ('F', 'Friday')], help_text='Day for the service', max_length=1)),
                ('calendar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Calendar')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('first_name', models.CharField(help_text='Enter First Name', max_length=20)),
                ('middle_name', models.CharField(help_text='Enter Middle Name', max_length=20, null=True)),
                ('last_name', models.CharField(help_text='Enter Last Name', max_length=20)),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this student', primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Student'),
        ),
    ]
