# Generated by Django 2.1.1 on 2018-09-17 21:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter title for this schedule', max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('MATH', 'Math'), ('ELA', 'ELA')], default=None, help_text='Subject', max_length=4)),
                ('service_type', models.CharField(choices=[('PI', 'Push-In'), ('PO', 'Pull-Out')], default=None, help_text='Service type', max_length=2)),
                ('total_time_req', models.IntegerField(help_text='Enter total time required')),
                ('satisfied', models.BooleanField(help_text='Check if this service has been satisfied')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('M', 'Monday'), ('Tu', 'Tuesday'), ('W', 'Wednesday'), ('Th', 'Thursday'), ('F', 'Friday')], help_text='Day for the service', max_length=1)),
                ('duration', models.IntegerField(help_text='Enter duration of this service (in minutes)')),
                ('calendar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Schedule')),
                ('service', models.ForeignKey(help_text='The particular service this belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('first_name', models.CharField(help_text='Enter First Name', max_length=20)),
                ('middle_name', models.CharField(blank=True, help_text='Enter Middle Name', max_length=20, null=True)),
                ('last_name', models.CharField(help_text='Enter Last Name', max_length=20)),
                ('serviced', models.BooleanField(default=False, help_text='Check if the services for this student have been completed')),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this student', primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Student'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ServiceInstance'),
        ),
    ]
