# Generated by Django 2.1.1 on 2018-09-21 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter title for this schedule', max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('MATH', 'Math'), ('ELA', 'ELA')], default=None, help_text='Subject', max_length=4)),
                ('service_type', models.CharField(choices=[('Push-In', 'Push-In'), ('Pull-Out', 'Pull-Out')], default=None, help_text='Service type', max_length=8)),
                ('total_time_req', models.IntegerField(help_text='Enter total time required')),
                ('satisfied', models.BooleanField(help_text='Check if this service has been satisfied')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], help_text='Day for the service', max_length=9)),
                ('time_start', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('time_end', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('duration', models.IntegerField(help_text='Enter duration of this service (in minutes)')),
                ('scheduled_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sched_serviceinstances', to='app.Schedule')),
                ('service', models.ForeignKey(help_text='The particular service this belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stud_serviceinstances', to='app.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('first_name', models.CharField(help_text='Enter First Name', max_length=20)),
                ('middle_name', models.CharField(blank=True, help_text='Enter Middle Name', max_length=20, null=True)),
                ('last_name', models.CharField(help_text='Enter Last Name', max_length=20)),
                ('serviced', models.BooleanField(default=False, help_text='Check if the services for this student have been completed')),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this student', primary_key=True, serialize=False)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='app.Student'),
        ),
    ]
