# Generated by Django 2.1.1 on 2018-09-17 21:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this student', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ServiceInstance'),
        ),
    ]
