# Generated by Django 2.1.1 on 2018-09-21 06:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_schedule_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceinstance',
            name='time_end',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='serviceinstance',
            name='time_start',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
