# Generated by Django 2.1.1 on 2018-09-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180917_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceinstance',
            old_name='calendar',
            new_name='scheduled_for',
        ),
        migrations.AlterField(
            model_name='serviceinstance',
            name='day',
            field=models.CharField(choices=[('M', 'Monday'), ('Tu', 'Tuesday'), ('W', 'Wednesday'), ('Th', 'Thursday'), ('F', 'Friday')], help_text='Day for the service', max_length=2),
        ),
    ]
