# Generated by Django 2.1.1 on 2018-09-18 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180917_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='services',
        ),
        migrations.AlterField(
            model_name='service',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='app.Student'),
        ),
        migrations.AlterField(
            model_name='serviceinstance',
            name='scheduled_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sched_serviceinstances', to='app.Schedule'),
        ),
        migrations.AlterField(
            model_name='serviceinstance',
            name='service',
            field=models.ForeignKey(help_text='The particular service this belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stud_serviceinstances', to='app.Service'),
        ),
    ]
